version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.hmdp_mysql
    container_name: hmdp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: yue99520
    ports:
      - "3306:3306"
      - "33060:33060"
      - "33061:33061"
    command:
     - --default-authentication-plugin=mysql_native_password
     - --bind-address=0.0.0.0
     - --sql_mode=NO_ENGINE_SUBSTITUTION
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: hmdp-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
